name: Check All Docker Tag Timestamps

on:
  workflow_dispatch:

jobs:
  check-docker-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Query all Docker tags and show their update timestamps
        run: |
          echo "Fetching all tags for adamwilsonlab/emma..."
          curl -s "https://hub.docker.com/v2/repositories/adamwilsonlab/emma/tags/?page_size=100" | \
            jq -r '.results[] | "\(.name): \(.last_updated)"'
