name: Check Earth Engine API in Multiple Python Paths

on:
  workflow_dispatch:

jobs:
  check-ee:
    runs-on: ubuntu-latest
    container:
      image: adamwilsonlab/emma:latest

    steps:
      - name: Check if `ee` is importable in /opt/conda/bin/python3
        run: |
          echo "🔍 Checking /opt/conda/bin/python3"
          if [ -x /opt/conda/bin/python3 ]; then
            /opt/conda/bin/python3 -m pip show earthengine-api || echo "❌ earthengine-api not found"
            /opt/conda/bin/python3 -c "import ee; print('✅ import ee OK:', ee.__version__)" || echo "❌ import ee failed"
          else
            echo "❌ /opt/conda/bin/python3 does not exist"
          fi

      - name: Check if `ee` is importable in /usr/bin/python3
        run: |
          echo "🔍 Checking /usr/bin/python3"
          if [ -x /usr/bin/python3 ]; then
            /usr/bin/python3 -m pip show earthengine-api || echo "❌ earthengine-api not found"
            /usr/bin/python3 -c "import ee; print('✅ import ee OK:', ee.__version__)" || echo "❌ import ee failed"
          else
            echo "❌ /usr/bin/python3 does not exist"
          fi

      - name: Check if `ee` is importable in /bin/python3
        run: |
          echo "🔍 Checking /bin/python3"
          if [ -x /bin/python3 ]; then
            /bin/python3 -m pip show earthengine-api || echo "❌ earthengine-api not found"
            /bin/python3 -c "import ee; print('✅ import ee OK:', ee.__version__)" || echo "❌ import ee failed"
          else
            echo "❌ /bin/python3 does not exist"
          fi
