name: Check Earth Engine API in Multiple Python Paths

on:
  workflow_dispatch:

jobs:
  check-ee:
    runs-on: ubuntu-latest
    container:
      image: adamwilsonlab/emma:latest

    steps:
      - name: Check for earthengine-api in r-reticulate
        run: |
          echo "Checking pip list:"
          /opt/conda/envs/r-reticulate/bin/pip list | grep earthengine
          echo "Trying Python import and version check:"
          /opt/conda/envs/r-reticulate/bin/python -c "import ee; print(ee.__version__)"
