name: Which Python in Docker

on:
  workflow_dispatch:

jobs:
  which-python:
    runs-on: ubuntu-latest
    container:
      image: adamwilsonlab/emma:latest

    steps:
      - name: Check which python and python3
        run: |
          echo "🔍 which python:"
          which python || echo "python not found"

          echo "🔍 which python3:"
          which python3 || echo "python3 not found"

          echo "🔍 which -a python:"
          which -a python || echo "python (all) not found"

          echo "🔍 which -a python3:"
          which -a python3 || echo "python3 (all) not found"

          echo "🔍 python3 version:"
          python3 --version || echo "python3 --version failed"

          echo "🔍 python version:"
          python --version || echo "python --version failed"
